# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post-api.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epost-api.proto\x12\x05posts\"2\n\x0e\x41\x64\x64PostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"J\n\x11UpdatePostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07post_id\x18\x02 \x01(\x05\x12\x13\n\x0bnew_content\x18\x03 \x01(\t\"5\n\x11\x44\x65letePostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07post_id\x18\x02 \x01(\x05\"!\n\x0eGetPostRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\"*\n\x0fGetPostsRequest\x12\x17\n\x0fnumber_of_posts\x18\x01 \x01(\x05\"\"\n\x0f\x41\x64\x64PostResponse\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\"%\n\x12UpdatePostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"%\n\x12\x44\x65letePostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"3\n\x0fGetPostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"9\n\x10GetPostsResponse\x12%\n\x05posts\x18\x01 \x03(\x0b\x32\x16.posts.GetPostResponse2\xc8\x02\n\x05Posts\x12:\n\x07\x41\x64\x64Post\x12\x15.posts.AddPostRequest\x1a\x16.posts.AddPostResponse\"\x00\x12\x43\n\nUpdatePost\x12\x18.posts.UpdatePostRequest\x1a\x19.posts.UpdatePostResponse\"\x00\x12\x43\n\nDeletePost\x12\x18.posts.DeletePostRequest\x1a\x19.posts.DeletePostResponse\"\x00\x12:\n\x07GetPost\x12\x15.posts.GetPostRequest\x1a\x16.posts.GetPostResponse\"\x00\x12=\n\x08GetPosts\x12\x16.posts.GetPostsRequest\x1a\x17.posts.GetPostsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDPOSTREQUEST']._serialized_start=25
  _globals['_ADDPOSTREQUEST']._serialized_end=75
  _globals['_UPDATEPOSTREQUEST']._serialized_start=77
  _globals['_UPDATEPOSTREQUEST']._serialized_end=151
  _globals['_DELETEPOSTREQUEST']._serialized_start=153
  _globals['_DELETEPOSTREQUEST']._serialized_end=206
  _globals['_GETPOSTREQUEST']._serialized_start=208
  _globals['_GETPOSTREQUEST']._serialized_end=241
  _globals['_GETPOSTSREQUEST']._serialized_start=243
  _globals['_GETPOSTSREQUEST']._serialized_end=285
  _globals['_ADDPOSTRESPONSE']._serialized_start=287
  _globals['_ADDPOSTRESPONSE']._serialized_end=321
  _globals['_UPDATEPOSTRESPONSE']._serialized_start=323
  _globals['_UPDATEPOSTRESPONSE']._serialized_end=360
  _globals['_DELETEPOSTRESPONSE']._serialized_start=362
  _globals['_DELETEPOSTRESPONSE']._serialized_end=399
  _globals['_GETPOSTRESPONSE']._serialized_start=401
  _globals['_GETPOSTRESPONSE']._serialized_end=452
  _globals['_GETPOSTSRESPONSE']._serialized_start=454
  _globals['_GETPOSTSRESPONSE']._serialized_end=511
  _globals['_POSTS']._serialized_start=514
  _globals['_POSTS']._serialized_end=842
# @@protoc_insertion_point(module_scope)
